POST http://localhost:3000/events
Content-Type: application/json

{
  "title": "Unite Summit",
  "details": "Um evento para quem é apaixonado por programação",
  "maximumAttendees": 100,
}

###

POST http://localhost:3000/events/49281799-0e2b-416f-b261-894ecc38ef38/attendees
Content-Type: application/json

{
  "name": "Pedro Mendes",
  "email": "pedrohenrique@gmail.com"
}

###

GET http://localhost:3000/events/49281799-0e2b-416f-b261-894ecc38ef38
Content-Type: application/json

###

GET http://localhost:3000/attendees/1/badge
Content-Type: application/json

###

GET http://localhost:3000/attendees/1/check-in
Content-Type: application/json